# workflow/Snakefile
import os

configfile: "config.yaml"

SAMPLES = list(config["samples"].keys())
OUTDIR = config["output"]["dir"]

include: "rules/common.smk"
include: "rules/qc_fastp.smk"
include: "rules/align_star.smk"
include: "rules/bam_post.smk"
include: "rules/signal_5prime.smk"
include: "rules/tracks.smk"
include: "rules/bigwig_compare.smk"
include: "rules/motif_anchor.smk"
include: "rules/motif_de_novo.smk"
include: "rules/metaplot.smk"

BIGWIG_TARGETS = []
BIGWIG_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.bamCPM.noblacklist.bw", sample=SAMPLES)
BIGWIG_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.R2firstbaseCPM.noblacklist.bw", sample=SAMPLES)
if FILTER_BLACKLIST:
    BIGWIG_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.bamCPM.blacklist.bw", sample=SAMPLES)
    BIGWIG_TARGETS += expand(f"{OUTDIR}/bigwig/{{sample}}/{{sample}}.R2firstbaseCPM.blacklist.bw", sample=SAMPLES)

rule all:
    default_target: True
    input:
        # QC
        expand(f"{OUTDIR}/qc/fastp/{{sample}}/merged_fastp_final.html", sample=SAMPLES),
        expand(f"{OUTDIR}/qc/fastp/{{sample}}/merged_fastp_final.json", sample=SAMPLES),
        f"{OUTDIR}/qc/star/short_read_mapping_summary.tsv",
        f"{OUTDIR}/qc/multiqc/multiqc_report.html",

        # Alignment (final BAM kept)
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.unique.mapq11.sorted.bam", sample=SAMPLES),
        expand(f"{OUTDIR}/star/{{sample}}/{{sample}}.unique.mapq11.sorted.bam.bai", sample=SAMPLES),

        # BigWig from BAM and 5' end signal; blacklist tracks are optional.
        BIGWIG_TARGETS,

        # Track files
        expand(f"{OUTDIR}/tracks/{{sample}}/{{sample}}.tracks.txt", sample=SAMPLES),

        # bigwigCompare log2(IP/Input) tracks (optional)
        BIGWIG_COMPARE_TARGETS,

        # Motif-anchored 1-nt m6A sites (optional)
        MOTIF_TARGETS,

        # Independent, strand-aware RT-termination de novo motif discovery
        DE_NOVO_MOTIF_TARGETS,

        # Strand-aware TSS-TES metaplots for both signal types
        METAPLOT_TARGETS,
